name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # <-- wichtig! Volles Checkout

      - name: Run HACS validation
        uses: hacs/action@main
