name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Wichtig, um später den main-Branch verfügbar zu haben

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV

      - name: Update manifest.json with tag version
        run: |
          sed -i 's/"version": *"[^"]*"/"version": "'"$VERSION"'"/' custom_components/enpal_website/manifest.json

      - name: Zip component
        run: |
          mkdir release
          cd custom_components
          zip -r ../release/enpal_website.zip enpal_website
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/enpal_website.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated manifest.json to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Hole und schalte auf main um
          git fetch origin main
          git checkout main

          # Kopiere die geänderte Datei aus dem Tag-Checkout in den main-Branch
          cp custom_components/enpal_website/manifest.json ./custom_components/enpal_website/manifest.json

          git add custom_components/enpal_website/manifest.json
          git commit -m "🔖 Set version to $VERSION in manifest.json (post-release)"
          git push origin main
