name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*'
permissions:
  contents: write

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip component
        run: |
          mkdir release
          cd custom_components
          zip -r ../release/enpal_website.zip enpal_website
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/enpal_website.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
